# Generated by Django 5.1.1 on 2024-10-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='photos/%Y%m%d')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
