# Generated by Django 5.1.1 on 2024-10-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
